#!/usr/bin/env bash

# Screen lock (gtk) if swayidle detect's no activity for 300 seconds. (5 min)
#swayidle -w \
	#timeout <time> '<command>' \
	#resume '<command>'

#timeout 300 '~/sync/system/script/dots/lock_wp.sh' \
#timeout 310 'hyprctl dispatch dpms off' \
#resume 'hyprctl dispatch dpms on' \

swayidle -w \
        timeout 120 'hyprctl dispatch dpms off' \
	resume 'hyprctl dispatch dpms on'
	#resume 'hyprctl dispatch dpms on' \
	#timeout 30 '~/sync/system/script/dots/lock_wp.sh' \
