:PROPERTIES:
:ID:       fd9a97e4-acc3-4bb1-aa66-6a170e5cf9ae
:END:
#+title: Asynthe's systems flake
#+property: header-args :tangle flake.nix
#+auto_tangle: t

* Table of Contents :toc:
- [[#description][Description]]
- [[#start---opening-bracket][Start - Opening bracket]]
- [[#outputs][Outputs]]
- [[#machines][Machines]]
  - [[#linux][Linux]]
  - [[#home-manager][Home Manager]]
  - [[#macos-apple-silicon][MacOS (Apple Silicon)]]
  - [[#not-used-for-now---android-nix-on-droid][Not Used for Now - Android (Nix On Droid)]]
- [[#inputs][Inputs]]
  - [[#opening-bracket][Opening Bracket]]
  - [[#nixpkgs-and-nixpkgs-stable][Nixpkgs and Nixpkgs Stable]]
  - [[#home-manager-1][Home Manager]]
  - [[#apps-and-repos][Apps and Repos]]
  - [[#nix-configuration-not-added][Nix Configuration (Not added)]]
- [[#end---closing-bracket][End - Closing bracket]]

* Description

[INSERT COOL IMAGE HERE]

Linux system
Laptop -> genkai

- /core_server.nix/ contains all that regular system must have.
- /genkai/ contains my current sy
- _basic.nix_ is contained inside _genkai_
- nor /core_server/ nor /genkai/ replaces coreutils

Home manager
- everything else
- hacking tools
home-manager replaces coreutils with the rust uutils

* Start - Opening bracket

Start!
#+begin_src nix
{
  description = "asynthe's system flake";
#+end_src

* Outputs

#+begin_src nix
outputs = inputs @ {
  self,
  nixpkgs,
  #nixpkgs-stable,
  #nixpkgs-wayland,
  #nix-on-droid,
  nix-darwin,
  #nix-gaming,
  home-manager,
  hyprland,
  musnix,
  ...
	}: let

  username = "asynthe";
  hostname = "genkai";
  username_mac = "benjamindunstan";
  hostname_mac = "Benjis-Macbook";
  linux_64 = "x86_64-linux";
  apple_silicon = "aarch64-darwin";
  pkgs = nixpkgs.legacyPackages.x86_64-linux;
  
  in {
#+end_src

*In {* is here as it gives me more flexibility for moving the org boxes.

* Machines
** Linux

#+begin_src nix
  nixosConfigurations = {
#+end_src

*** Server (basic)

This basic server configures:
- Networking
- Filesystems

#+begin_src nix
  basic = nixpkgs.lib.nixosSystem {
    system = "${hostname}";
    specialArgs = {inherit username inputs;};
    modules = [
      ./machines/linux/basic
     ];
  };
#+end_src

*** Laptop (genkai)

This configures more specific things such as:
- Audio
- Drivers
- More networking
- systemd Timers
- Services
- Window Managers
- Extra
- Tools

#+begin_src nix
  genkai = nixpkgs.lib.nixosSystem {
    system = "${hostname}";
    specialArgs = {inherit username inputs;};
    modules = [
      ./machines/linux/laptop
      inputs.musnix.nixosModules.musnix
      # HOME MANAGER AS A MODULE GOES HERE
      ];
    };
  };
#+end_src

*** Home Manager as Module

Disabled for now, but you can play around with it.

#+begin_src nix
      #home-manager.nixosModules.home-manager {
      #home-manager = {
      #useGlobalPkgs = true;
      #useUserPackages = true;
      #users.${username} = import ./nix/home/linux/home.nix;
      #};
      #}

      # Testing Specialargs on Home Manager Module
      #nixosConfigurations.${hostname} = { nixpkgs.lib.nixosSystem rec {
      #({ config, lib, ... }: {
      #options.home-manager.users = lib.mkOption {
      #type = with lib.types; attrsOf (submoduleWith {
      #specialArgs = { super = config; inherit helix; };
      #});
      #};
      #})
#+end_src

** Home Manager

_note_: GNU coreutils is replaced with Rust's [[https://github.com/uutils/coreutils][uutils]].

Home Manager as a Standalone
#+begin_src nix
  homeConfigurations = {
    ${username} = home-manager.lib.homeManagerConfiguration {
      inherit pkgs;
      extraSpecialArgs = {inherit username inputs;};
      modules = [
        ./modules/home
      ];
    };
  };
#+end_src

only-user? (check pls)

##+begin_src nix
  only_user = home-manager.lib.homeManagerConfiguration {
    inherit pkgs;
    extraSpecialArgs = {inherit username inputs;};
    modules = [ ./modules/home/user ];
  };
##+end_src

** MacOS (Apple Silicon)

#+begin_src nix
  darwinConfigurations = {
#+end_src

*** M1 Macbook

*Resources*
+ [[https://gist.github.com/jmatsushita/5c50ef14b4b96cb24ae5268dab613050][Setup nix, nix-darwin and home-manager from scratch on an M1 Macbook Pro - gist.github.com]]
+ [[https://github.com/MatthiasBenaets/nixos-config#nix-darwin-installation-guide][nixos-config / MatthiasBenaets - github]]

darwin-rebuild switch --flake .

#+begin_src nix
  ${hostname_mac} = nix-darwin.lib.darwinSystem {
    system = "${apple_silicon}";
    specialArgs = {inherit username_mac inputs;};
      modules = [
        ./machines/macos
      ];
  };
};
#+end_src

  macOS configuration
    darwinConfigurations =
      let
        system = x64_darwin;
        specialArgs =
        {
          inherit username_mac;
          nixpkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
            };
        }
        // inputs;
       base_args = {
       inherit nix-darwin home-manager system specialArgs nixpkgs;
      };
      in {
      macos = macosSystem (base_args // {
      darwin-modules = [ ./system/macos ];
      home-module = import ./home/darwin;
      });
      };
111#+end_src

** Not Used for Now - Android (Nix On Droid)

Interesting, might use.

#+begin_src nix
  #nixOnDroidConfigurations.default =
    #nix-on-droid.lib.nixOnDroidConfiguration {
      #modules = [
        #./nix/nix-on-droid
      #];
    #};
#+end_src

* Inputs
** Opening Bracket

#+begin_src nix
};
 inputs = {
#+end_src

** Nixpkgs and Nixpkgs Stable

#+begin_src nix
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixpkgs-stable.url = "github:nixos/nixpkgs/nixos-23.05";
#+end_src

** Home Manager

#+begin_src nix
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs"; 
      # Follows the nixpkgs channel defined before, 
      # to avoid different versions of nixpkgs deps problems.
    };
#+end_src

*NIX DARWIN*
##+begin_src nix
    # For MacOS
    nixpkgs-darwin.url = "github:nixos/nixpkgs/nixpkgs-23.05-darwin";
    nix-darwin = {
      url = "github:lnl7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };
  };
##+end_src

*NIX ON DROID*
#+begin_src nix
    #nix-on-droid = {
      #url = "github:t184256/nix-on-droid/release-23.05";
      #inputs.nixpkgs.follows = "nixpkgs-stable";
      #};
#+end_src

** Apps and Repos

- [[https://github.com/hyprwm/Hyprland][Hyprland]]
#+begin_src nix
hyprland.url = "github:hyprwm/Hyprland";
#+end_src

+ [[https://github.com/musnix/musnix][musnix]]
#+begin_src nix
musnix.url = "github:musnix/musnix";
#+end_src

nil - Nix Language server
+ [[https://github.com/oxalica/nil][github page]]
#+begin_src nix
nil.url = "github:oxalica/nil";
#+end_src

rust-overlay
+ [[https://github.com/oxalica/rust-overlay][rust-overlay - github page]]
#+begin_src nix
rust-overlay.url = "github:oxalica/rust-overlay";
#+end_src

*** Uncommented

#+begin_src nix
    #nixpkgs-wayland.url = "github:nix-community/nixpkgs-wayland";
    #nix-gaming.url = "github:fufexan/nix-gaming";
    #helix.url = "github:helix-editor/helix/23.05";
#+end_src

** Nix Configuration (Not added)
* End - Closing bracket

Thanks for Reading!
#+begin_src nix
};
}
#+end_src
