#!/usr/bin/env bash

set -x
os=$(uname -s)

# Linux
if [ "$os" = "Linux" ]; then
    echo "This is a Linux system."

    # Flakes
    git -C ~/sync/flakes add -A
    git -C ~/sync/flakes commit -m 'update'
    git -C ~/sync/flakes push

    # Notes
    git -C ~/sync/notes add -A
    git -C ~/sync/notes commit -m 'update'
    git -C ~/sync/notes push

    # Keys
    git -C ~/sync/pass add -A
    git -C ~/sync/pass commit -m 'update'
    git -C ~/sync/pass push

    # Study
    git -C ~/sync/study add -A
    git -C ~/sync/study commit -m 'update'
    git -C ~/sync/study push

    # Personal flake
    git -C ~/sync/yuugen add -A
    git -C ~/sync/yuugen commit -m 'update'
    git -C ~/sync/yuugen push

# macOS
elif [ "$os" = "Darwin" ]; then
    echo "This is a macOS system."

    # Flakes
    git -C ~/sync/flakes add -A
    git -C ~/sync/flakes commit -m 'update'
    git -C ~/sync/flakes push

    # Notes
    git -C ~/sync/notes add -A
    git -C ~/sync/notes commit -m 'update'
    git -C ~/sync/notes push

    # Keys
    git -C ~/sync/pass add -A
    git -C ~/sync/pass commit -m 'update'
    git -C ~/sync/pass push

    # Study
    git -C ~/sync/study add -A
    git -C ~/sync/study commit -m 'update'
    git -C ~/sync/study push --recurse-submodules

    # Personal flake
    git -C ~/sync/yuugen add -A
    git -C ~/sync/yuugen commit -m 'update'
    git -C ~/sync/yuugen push

else
    echo "Unsupported operating system: $os"
    exit 1
fi
