#! /usr/bin/env bash

# 1. disable starship icons, or icons in term

# 2. change lf for regular lf

# 3. change mpv to drm mpv
#sed? then go again

# if run once
# tty-mode -> on
# if run again
# tty-mode -> off
