#+title: Yabai's configuration
#+property: header-args :tangle yabairc
#+auto_tangle: t

Restart service: *yabai --restart-service*

* Info and links

This is my yabai configuration with guide for my work's M1 MacBook Air

+ [[https://github.com/koekeishiya/yabai][yabai - github page]]
+ [[https://bryce-s.com/yabai/][MacOS - Yabai Configuration - bryce-s.com]]

* Tips
** Tiling certain apps

+ [[https://github.com/koekeishiya/yabai/issues/727][How do I only tile certain apps? #727 - github.com]]
+ [[https://github.com/koekeishiya/yabai/issues/86][Getting Emacs to tile #86 - github.com]]

  Tile emacs
  ~$ yabai -m rule --add app=Emacs manage=on~

  Untile Finder
  ~$ yabai -m rule --add manage=off app="Finder"~

  Float every app except Safari, Finder, and Notes.
  ~$ yabai -m rule --add app!="^(Safari|Finder|Notes)$" manage=off~

* Installation
** Disabling System Integrity Protection (Complete or Partial)

Once you're inside this mode, open a terminal and run:
~$ csrutil enable --without fs --without debug --without nvram~
Accept the printed warning then reboot.

After you boot, you will have to enable non-Apple-signed arm64e binaries like this.
~$ sudo nvram boot-args=-arm64e_preview_abi~

Once you're done, open a terminal and check that SIP is disabled with.
~$ csrutil status~

This can show you both
~System Integrity Protection status: disabled~
or
~System Integrity Protection status: unknown~ which means it's partially disabled.

** Installing
** Configuring scripting addition
* Configuration
** Shebang

#+begin_src config
#!/usr/bin/env sh
#+end_src

** Scripting addition

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

#+begin_src config
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#+end_src

** Global Settings
*** Default (disabled)

/#+begin_src config
yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          on             \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap
/#+end_src

*** Rice

#+begin_src config
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
#+end_src

# general space settings
#+begin_src config
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
#+end_src

** End

#+begin_src config
echo "yabai configuration loaded.."
#+end_src
