#!/bin/sh

# list of desired + ls
# mkdir + ls
# cd + ls
#alias mkd='mkcdir'
# Make a directory then cd into it, use quotes when doing various dirs

mkcdir ()
{
    mkdir -p -- "$1" &&
       cd -P -- "$1"
}
